// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC10T8pl7U8w14C73wdcZg_Gsjoxy-USnI',
    appId: '1:1078476335702:web:3ad936cad37eb7cdc829f7',
    messagingSenderId: '1078476335702',
    projectId: 'storepro-55dd4',
    authDomain: 'storepro-55dd4.firebaseapp.com',
    storageBucket: 'storepro-55dd4.firebasestorage.app',
    measurementId: 'G-GJJP2TLCKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMm0ZbH20HnSZA9oLua4CyPV7m0iwNH2M',
    appId: '1:1078476335702:android:0a653ef313b373dfc829f7',
    messagingSenderId: '1078476335702',
    projectId: 'storepro-55dd4',
    storageBucket: 'storepro-55dd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYEhqzKu11KGf_48FmYj9wVqvTMrnvwCg',
    appId: '1:1078476335702:ios:8da81d3b607a4d97c829f7',
    messagingSenderId: '1078476335702',
    projectId: 'storepro-55dd4',
    storageBucket: 'storepro-55dd4.firebasestorage.app',
    iosBundleId: 'com.example.storepro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYEhqzKu11KGf_48FmYj9wVqvTMrnvwCg',
    appId: '1:1078476335702:ios:8da81d3b607a4d97c829f7',
    messagingSenderId: '1078476335702',
    projectId: 'storepro-55dd4',
    storageBucket: 'storepro-55dd4.firebasestorage.app',
    iosBundleId: 'com.example.storepro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC10T8pl7U8w14C73wdcZg_Gsjoxy-USnI',
    appId: '1:1078476335702:web:99906823ff5d987dc829f7',
    messagingSenderId: '1078476335702',
    projectId: 'storepro-55dd4',
    authDomain: 'storepro-55dd4.firebaseapp.com',
    storageBucket: 'storepro-55dd4.firebasestorage.app',
    measurementId: 'G-5VEGP22K3P',
  );
}
